/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.prj666.group1.petadoptionsystem.api;

import com.prj666.group1.petadoptionsystem.dto.AdopterPreferencesPostRequest;
import com.prj666.group1.petadoptionsystem.dto.ModelApiResponse;
import com.prj666.group1.petadoptionsystem.dto.Recommendation;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-11-06T19:39:54.912418600-05:00[America/Toronto]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "adopter", description = "the adopter API")
@RequestMapping("${openapi.petAdoptionSystem.base-path:/api/v2}")
public interface AdopterApi {

    /**
     * POST /adopter/preferences : Add a preference for pet attributes
     *
     * @param adopterPreferencesPostRequest  (required)
     * @return Preference added successfully (status code 201)
     */
    @Operation(
        operationId = "adopterPreferencesPost",
        summary = "Add a preference for pet attributes",
        responses = {
            @ApiResponse(responseCode = "201", description = "Preference added successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/adopter/preferences",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ModelApiResponse> adopterPreferencesPost(
        @Parameter(name = "AdopterPreferencesPostRequest", description = "", required = true) @Valid @RequestBody AdopterPreferencesPostRequest adopterPreferencesPostRequest
    );


    /**
     * GET /adopter/recommendations : Get a list of recommended pets based on preferences
     *
     * @return A list of recommended pets (status code 200)
     */
    @Operation(
        operationId = "adopterRecommendationsGet",
        summary = "Get a list of recommended pets based on preferences",
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of recommended pets", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Recommendation.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/adopter/recommendations",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<Recommendation>> adopterRecommendationsGet(
        
    );

}
