/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.prj666.group1.petadoptionsystem.api;

import com.prj666.group1.petadoptionsystem.dto.Adoption;
import com.prj666.group1.petadoptionsystem.dto.AdoptionPostRequest;
import com.prj666.group1.petadoptionsystem.dto.AdoptionStatusGet200Response;
import com.prj666.group1.petadoptionsystem.dto.AdoptionStoryGet200Response;
import com.prj666.group1.petadoptionsystem.dto.ModelApiResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-11T06:31:19.046953700-05:00[America/Toronto]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "adoption", description = "Operations about Adoptions")
@RequestMapping("${openapi.petAdoptionSystem.base-path:}")
public interface AdoptionApi {

    /**
     * PUT /adoption/{id}/cancel : Cancel adoption
     * Adopter cancels adoption
     *
     * @param id The ID of the adoption to cancel (required)
     * @return Generic API response (status code 200)
     *         or Generic API response (status code 401)
     */
    @Operation(
        operationId = "adoptionIdCancelPut",
        summary = "Cancel adoption",
        description = "Adopter cancels adoption",
        tags = { "adoption" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Generic API response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Generic API response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/adoption/{id}/cancel",
        produces = { "application/json" }
    )
    
    ResponseEntity<ModelApiResponse> adoptionIdCancelPut(
        @Parameter(name = "id", description = "The ID of the adoption to cancel", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    );


    /**
     * PUT /adoption/{id}/status : Retrieve adoption status
     * Fetches the current status of adoptions for the authenticated adopter.
     *
     * @param id The ID of the adoption to update (required)
     * @param adoption  (required)
     * @return Generic API response (status code 200)
     *         or Generic API response (status code 401)
     */
    @Operation(
        operationId = "adoptionIdStatusPut",
        summary = "Retrieve adoption status",
        description = "Fetches the current status of adoptions for the authenticated adopter.",
        tags = { "adoption" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Generic API response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Generic API response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/adoption/{id}/status",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ModelApiResponse> adoptionIdStatusPut(
        @Parameter(name = "id", description = "The ID of the adoption to update", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "Adoption", description = "", required = true) @Valid @RequestBody Adoption adoption
    );


    /**
     * POST /adoption : Creates new adoption
     * Creates new adoption
     *
     * @param adoptionPostRequest  (required)
     * @return Generic API response (status code 200)
     *         or Generic API response (status code 401)
     */
    @Operation(
        operationId = "adoptionPost",
        summary = "Creates new adoption",
        description = "Creates new adoption",
        tags = { "adoption" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Generic API response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Generic API response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/adoption",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ModelApiResponse> adoptionPost(
        @Parameter(name = "AdoptionPostRequest", description = "", required = true) @Valid @RequestBody AdoptionPostRequest adoptionPostRequest
    );


    /**
     * GET /adoption/status : Retrieve adoption status
     * Fetches the current status of adoptions for the authenticated adopter.
     *
     * @return Adoption status retrieved successfully (status code 200)
     *         or Generic API response (status code 401)
     */
    @Operation(
        operationId = "adoptionStatusGet",
        summary = "Retrieve adoption status",
        description = "Fetches the current status of adoptions for the authenticated adopter.",
        tags = { "adoption" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Adoption status retrieved successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdoptionStatusGet200Response.class))
            }),
            @ApiResponse(responseCode = "401", description = "Generic API response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/adoption/status",
        produces = { "application/json" }
    )
    
    ResponseEntity<AdoptionStatusGet200Response> adoptionStatusGet(
        
    );


    /**
     * GET /adoption/story : Retrieve a list of adoption stories
     * Returns a list of adoption stories with the specified number of objects.
     *
     * @param N The number of adoption story objects to return (optional, default to 5)
     * @return A list of adoption stories (status code 200)
     */
    @Operation(
        operationId = "adoptionStoryGet",
        summary = "Retrieve a list of adoption stories",
        description = "Returns a list of adoption stories with the specified number of objects.",
        tags = { "adoption" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of adoption stories", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdoptionStoryGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/adoption/story",
        produces = { "application/json" }
    )
    
    ResponseEntity<AdoptionStoryGet200Response> adoptionStoryGet(
        @Min(1) @Parameter(name = "N", description = "The number of adoption story objects to return", in = ParameterIn.QUERY) @Valid @RequestParam(value = "N", required = false, defaultValue = "5") Integer N
    );

}
