/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.prj666.group1.petadoptionsystem.api;

import com.prj666.group1.petadoptionsystem.dto.ModelApiResponse;
import com.prj666.group1.petadoptionsystem.dto.Recommendation;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-10-31T17:36:43.291576-04:00[America/Toronto]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "recommendation", description = "the recommendation API")
@RequestMapping("${openapi.petAdoptionSystem.base-path:/api/v1}")
public interface RecommendationApi {

    /**
     * POST /recommendation/{id}/accept : Accept a recommendation and create an adoption
     *
     * @param id The ID of the recommendation to accept (required)
     * @return Recommendation accepted, adoption created (status code 201)
     */
    @Operation(
        operationId = "recommendationIdAcceptPost",
        summary = "Accept a recommendation and create an adoption",
        responses = {
            @ApiResponse(responseCode = "201", description = "Recommendation accepted, adoption created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/recommendation/{id}/accept",
        produces = { "application/json" }
    )
    
    ResponseEntity<ModelApiResponse> recommendationIdAcceptPost(
        @Parameter(name = "id", description = "The ID of the recommendation to accept", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    /**
     * GET /recommendation/next : Get the next recommendation for the adopter
     *
     * @return The next recommendation item (status code 200)
     */
    @Operation(
        operationId = "recommendationNextGet",
        summary = "Get the next recommendation for the adopter",
        responses = {
            @ApiResponse(responseCode = "200", description = "The next recommendation item", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Recommendation.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/recommendation/next",
        produces = { "application/json" }
    )
    
    ResponseEntity<Recommendation> recommendationNextGet(
        
    );

}
